<?php

use Drupal\Core\Routing\TrustedRedirectResponse;
use Drupal\views\Views;

/**
 * @file
 * Functions to support theming in the GCWEB theme
 */

/**
 * Implements hook_preprocess_HOOK() for links--language-block.html.twig
 * provide language variable to the twig template
 */
function gcweb_preprocess_links__language_block(&$variables) {
  $variables['language'] = \Drupal::languageManager()->getCurrentLanguage()->getId();
}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig
 * redirect non-admin users of external pages to the external page
 * setup variables: date modified, canada.ca search form link and mega menu link for twig template
 */
function gcweb_preprocess_page(&$variables) {
  // find language
  $variables['langcode'] = \Drupal::languageManager()->getCurrentLanguage()->getId();

  if (is_object($node = \Drupal::request()->get('node'))) {
    // redirect all users except comment moderators and admins to dataset page
    if ($node->getType() == 'external') {
      $role = \Drupal::currentUser()->getRoles();
      if (!(in_array('comment_moderator',$role)) && !(in_array('administrator',$role))) {
        $translated_node = $node->getTranslation($variables['langcode']);
        $path = $translated_node->get('field_url')->getValue();
        $response = new TrustedRedirectResponse($path[0]['uri']);
        $response->send();
      }
    }

    // date modified
    $time = $node->getChangedTime();
    $variables['date_modified'] = \Drupal::service('date.formatter')->format($time, 'custom', 'Y-m-d');
  }
  else {
    $variables['date_modified'] = \Drupal::service('date.formatter')->format(time(), 'custom', 'Y-m-d');
  }

  // feedback link
  $variables['feedback_link'] = $variables['langcode'] == 'fr'
    ? '/fr/formulaire/faites-nous-part-de-vos-commentaires'
    : '/forms/contact-us';
}

/**
 * Implements template_preprocess_user()
 * add recent contents view to the login page
 * add recent comments view to the login page
 */
function gcweb_preprocess_user(&$variables) {
  // recent contents
  if (\Drupal::currentUser()->hasPermission('view any unpublished content')) {
    $content_recent = Views::getView('content_recent');
    if (is_object($content_recent)) {
      $content_recent->setDisplay('block_1');
      $content_recent->execute();
      $variables['content_recent'] = $content_recent->render();
    }
  }

  // recent comments
  if (\Drupal::currentUser()->hasPermission('administer comments')) {
    $comments_recent = Views::getView('comments_recent');
    if (is_object($comments_recent)) {
      $comments_recent->setDisplay('block_1');
      $comments_recent->execute();
      $variables['comments_recent'] = $comments_recent->render();
    }
  }
}

/**
 * Implements hook_preprocess_node()
 * attach highlight library to blog contents
 */
function gcweb_preprocess_node(&$variables) {
  $node = $variables['node'];
  if ($node->getType() === 'landing_page') {
    $variables['#attached']['library'][] = 'gcweb/highlight';
  }
}
